name: CI
on:
  push:
    branches-ignore:
      - index
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate registry
        uses: Amadevus/pwsh-script@v2
        with:
          script: |
            $entries = @()
            if ($github.base_ref) {
              # we are in a pull request, let's only check changed entries
              $baseRef = 'refs/heads/base'
              git fetch --depth=1 origin "+$($github.base_ref):$baseRef" | Out-Host
              # get a list of files changed in PR
              $entries = git diff-tree --no-commit-id --name-only $baseRef
            }
            ./.github/actions/validate-registry/action.yml -Entries $entries -Token $github.token